### ISSUE TITLE
Is core-js a dependency?

### ISSUE THREAD

**Issue by rumtraubenuss** [vonschau/next-routes-with-locale#14]
Is `core-js` a peer dependency? Without explicitly installing `core-js` in my project, starting the next app fails because of:

```
Error: Cannot find module 'core-js/modules/es.array.iterator'
...
 at Object.<anonymous> (xxx/node_modules/next-routes-with-locale/dist/index.js:5:1)
```

**Comment by iksent** [comment]
ha-ha, just opened same issue 1 minute ago

**Comment by iksent** [comment]
I am having also another error: 

```Cannot find module '@babel/runtime-corejs3/helpers/interopRequireDefault'```

**Comment by rumtraubenuss** [comment]
@iksent Did you install core-js 3? I also had your issue. Changing the babel setup to 3 was missing. For example in `.babelrc`
```
...
"preset-env": {
  "corejs": 3
  }
}
...
```

**Comment by iksent** [comment]
@rumtraubenuss, hello.
I did not have time to wait, and I was sure that the answer from the developer would not be given soon.
Therefore, I was forced to develop my own version of i18n subpaths.

**Comment by toltarisa** [comment]
> @rumtraubenuss, hello.
> I did not have time to wait, and I was sure that the answer from the developer would not be given soon.
> Therefore, I was forced to develop my own version of i18n subpaths.

Hi can you share your solution ? ,i'm using react-i18next but it does not have local subpath support

**Comment by vonschau** [comment]
I've added core-js as dependency because it is a dependency.
