### ISSUE TITLE
Errors while compile: Cannot find module

### ISSUE THREAD

**Issue by iksent** [vonschau/next-routes-with-locale#15]
Cannot find module @babel/runtime-corejs3/helpers/interopRequireDefault

If I add this babel's package by myself, then new error:

Cannot find module 'core-js/modules/es.array.iterator'

![2019-10-15_13-00-41](https://user-images.githubusercontent.com/32956521/66812285-07449980-ef4c-11e9-844d-e4623a059006.png)

**Comment by ViktorVojtek** [comment]
Hello, same issue here. Any solutions?

**Comment by robksawyer** [comment]
I was able to solve this by installing it via `yarn add @babel/runtime-corejs3`.

**Comment by chiqui3d** [comment]
Same problem here

**Comment by vonschau** [comment]
Hi all,

fixed in v1.8.4.
