### ISSUE TITLE
Cannot find module 'next/dist/lib/link.js'

### ISSUE THREAD

**Issue by gielcobben** [vonschau/next-routes-with-locale#9]
I upgraded to Next.js 8 and they changed the location of `Router.js` and `Link.js`. When running my next project I get the following Error: `Error: Cannot find module 'next/dist/lib/link.js'`. If I look into the next directory in my node_modules it's true. `next/dist/lib/link.js` should be `next/dist/client/link.js`. Same goes for the `router.js` file. 

I think updating next in your dependency should fix the error.

**Comment by manelgarcia** [comment]
same

**Comment by shadowangle** [comment]
any update?

**Comment by shadowangle** [comment]
@vonschau please can you update version and release? 👍 👍 👍 👍 👍

**Comment by deeartrama88** [comment]
any update?

**Comment by aplogman** [comment]
Yeah same?? Update?

**Comment by samuelg0rd0n** [comment]
Will this package be fixed for next.js 8 please?

**Comment by vonschau** [comment]
Hi guys,

I just upgraded Next.js and package is working again. Thanks for your patience.

V.
